apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: react-app

